apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: slops
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: slops                                                                                                                         
  labels:                                                                                                          
    app: gateway
  name: gateway
  namespace: slops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: ratnadeepb/slops-gateway:latest
        name: gateway
        ports:
        - containerPort: 9090
        