apiVersion: v1
kind: Service
metadata:
  name: slops-tracer
  namespace: slops
spec:
  ports:
    - port: 14268
      protocol: TCP
      targetPort: 14268
  selector:
    app: tracer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tracer
  name: tracer
  namespace: slops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tracer
  template:
    metadata:
      labels:
        app: tracer
    spec:
      containers:
        - image: ratnadeepb/slops-tracer:latest
          name: tracer
          ports:
            - containerPort: 14268
          env:
            - name: PORT
              value: "14268"
