apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-trace
  namespace: slops
spec:
  # strategy: production
  strategy: allInOne
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
