apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-trace
  namespace: slops
spec:
  strategy: production
  allInOne:
    # image: jaegertracing/all-in-one:latest
    options:
      log-level: debug
  storage:
    type: memory
    options:
      memory:
        max-traces: 500000
  ingress:
    enabled: false
  agent:
    strategy: DaemonSet
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  ui:
    options:
      search:
        maxLimit: 5000000