apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: slops
data:
  config.yaml: |
    service: "producer"
    sample_threshold: 0.5
    support: 0.01
    epsilon: 0.001
    partitions: 10
    http_port: 2048