apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: slops
data:
  config.yaml: |
    service: "producer"
    update_interval: 10
    update_interval_unit: "second"
    threshold: 50
    chg_percent: 10
    support: 0.01
    epsilon: 0.001
    partitions: 10
    grpc_port: 4000
    http_port: 2048