apiVersion: v1
kind: Service
metadata:
  name: producer
  namespace: slops
spec:
  ports:
  - port: 2048
    protocol: TCP
    targetPort: 2048
  selector:
    app: producer
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: slops                                                                                                                         
  labels:                                                                                                          
    app: producer
  name: producer
  namespace: slops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: ratnadeepb/slops-producer-state:latest
        name: producer
        ports:
        - containerPort: 62000
        volumeMounts:
        - name: config
          mountPath: /etc/producer/
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_BOOTSTRAP
          value: "ordergo-kafka-bootstrap:9092"
        - name: VANILLA
          # value: "true" # original Kafka
          value: "false" # SMALOPS
        - name: LOAD_IMBALANCE_TOLERANCE
          value: "10"
        - name: "REBALANCE_SLEEP_TIME"
          value: "500"
        - name: TRACER_NAME
          value: "producer"
        - name: TRACER_COLLECTOR
          value: http://jaeger-trace-collector:14268/api/traces
        - name: ENV
          value: Dev
      serviceAccountName: producer-accnt
      volumes:
      - name: config
        configMap:
          name: server-config